//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSchemaContainer : DbContext
    {
        public DBSchemaContainer()
            : base("name=DBSchemaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DCREvent> DCREvents { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<EventRole> EventRoles { get; set; }
        public virtual DbSet<EventGroup> EventGroups { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Includes> Includes { get; set; }
    }
}
