//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcrWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int ToEventId { get; set; }
        public int FromEventId { get; set; }
    
        public virtual DCREvent ToDCREvent { get; set; }
        public virtual DCREvent FromDCREvent { get; set; }
    }
}
