//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcrWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSchemaContainer : DbContext
    {
        public DBSchemaContainer()
            : base("name=DBSchemaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DCREvent> DCREvents { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<EventRole> EventRoles { get; set; }
        public virtual DbSet<EventGroup> EventGroups { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Includes> Includes { get; set; }
        public virtual DbSet<Excludes> Excludes { get; set; }
        public virtual DbSet<Conditions> Conditions { get; set; }
        public virtual DbSet<Responses> Responses { get; set; }
        public virtual DbSet<Milestones> Milestones { get; set; }
        public virtual DbSet<Children> Children { get; set; }
        public virtual DbSet<DCRGraph> DCRGraphs { get; set; }
        public virtual DbSet<GraphEvent> GraphEvents { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<EventUIElemement> EventUIElemements { get; set; }
        public virtual DbSet<IntegerSpecifyingUIElement> IntegerSpecifyingUIElements { get; set; }
    }
}
