//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcrWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCREvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DCREvent()
        {
            this.EventRoles = new HashSet<EventRole>();
            this.EventGroups = new HashSet<EventGroup>();
        }
    
        public int Id { get; set; }
        public string EventId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public string StatusMessageAfterExecution { get; set; }
        public bool Included { get; set; }
        public bool Pending { get; set; }
        public bool Executed { get; set; }
        public bool Parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRole> EventRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventGroup> EventGroups { get; set; }
    }
}
